# Generated by Django 5.0.1 on 2024-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_category_options_alter_meetings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'All Users',
            },
        ),
    ]
