# Generated by Django 5.0.1 on 2024-03-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_all_users_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users',
            name='email',
            field=models.EmailField(max_length=120),
        ),
        migrations.AlterField(
            model_name='all_users',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
    ]
