# Generated by Django 5.0.1 on 2024-03-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_all_users_email_alter_all_users_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
